export type {
  JSXPathSegment,
  JSXStructuralPath,
  TextEditAnchor,
  BatchOperation,
  ClientMessage,
  ServerMessage,
  ComponentInfo,
  UndoEntry,
  SiblingInfo,
  ControlType,
  PropertyGroup,
  PropertyDescriptor,
  EnumOption,
  TailwindTokenMap,
  TransformErrorCode,
  ElementIdentity,
  DetectionResult,
  ComponentRef,
  ToolType,
  TextAnnotation,
  ColorOverride,
  TextEditAnnotation,
  Annotation,
  CanvasUndoAction,
  RevertData,
  ChangeEntry,
} from "./types.js";

export type {
  RegistryItem,
  RegistryItemFull,
  ProjectConfig,
  RegistryProvider,
  WrittenFile,
} from "./registry-types.js";
